const RATE_LIMIT = { max: 100, ms: 60000 };
const CACHE_TTL_SEC = 300;
const DEFAULT_PER_PAGE = 50;
const MAX_PER_PAGE = 500;
const MAX_REQUEST_URL_LENGTH = 4096;
const MAX_SEARCH_QUERY_LENGTH = 200;
const MAX_FUZZY_SEARCH_DATASETS = 3;

module.exports = {
  RATE_LIMIT,
  CACHE_TTL_SEC,
  DEFAULT_PER_PAGE,
  MAX_PER_PAGE,
  MAX_REQUEST_URL_LENGTH,
  MAX_SEARCH_QUERY_LENGTH,
  MAX_FUZZY_SEARCH_DATASETS,
};
